import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/service_model.dart';

final passportServiceProvider = Provider<List<GeneralService>>((ref) {
  return [
    GeneralService(
      id: 'pass_new',
      category: 'Passport',
      name: 'New Passport Application',
      description: 'Apply for your first electronic passport using Fayda ID.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
      type: ServiceType.online,
      officialLink: 'https://www.passport.gov.et',
      instructionSteps: [
        'Get your 12-digit FIN from your Fayda ID card.',
        'Visit the official INAS portal.',
        'Select "New Passport" and enter your FIN.',
        'Choose your appointment date and office location.',
        'Pay the fee via Telebirr or CBE Birr.',
        'Print your appointment slip.'
      ],
      requirements: ['Fayda FIN', 'Birth Certificate', 'Telebirr/CBE Birr', 'Appointment Slip'],
      assistanceFee: 100.0,
    ),
    GeneralService(
      id: 'pass_renew',
      category: 'Passport',
      name: 'Passport Renewal',
      description: 'Renew your expiring passport with your digital ID.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
      type: ServiceType.online,
      officialLink: 'https://www.passport.gov.et',
      instructionSteps: [
        'Login to the INAS portal.',
        'Enter your old passport number and Fayda FIN.',
        'Upload a digital photo if required.',
        'Pay the renewal fee.',
        'Schedule your biometric data collection.'
      ],
      requirements: ['Old Passport', 'Fayda ID', 'Digital Photo'],
      assistanceFee: 100.0,
    ),
    GeneralService(
      id: 'pass_lost',
      category: 'Passport',
      name: 'Lost Passport Replacement',
      description: 'Replace your lost passport and get a new one issued.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
      type: ServiceType.online,
      officialLink: 'https://www.passport.gov.et',
      instructionSteps: [
        'Report the loss to the nearest police station.',
        'Obtain a police report document.',
        'Visit INAS portal and select "Lost Passport".',
        'Upload the police report and Fayda ID.',
        'Pay the replacement fee.',
        'Schedule biometric appointment.'
      ],
      requirements: ['Police Report', 'Fayda ID', 'Birth Certificate', 'Payment Receipt'],
      assistanceFee: 150.0,
    ),
    GeneralService(
      id: 'pass_damaged',
      category: 'Passport',
      name: 'Damaged Passport Replacement',
      description: 'Replace your damaged or mutilated passport.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
      type: ServiceType.online,
      officialLink: 'https://www.passport.gov.et',
      instructionSteps: [
        'Login to INAS portal.',
        'Select "Damaged Passport Replacement".',
        'Upload photos of the damaged passport.',
        'Enter your Fayda FIN for verification.',
        'Submit the old damaged passport at appointment.',
        'Pay the replacement fee.'
      ],
      requirements: ['Damaged Passport', 'Fayda ID', 'Digital Photos'],
      assistanceFee: 120.0,
    ),
    GeneralService(
      id: 'pass_stolen',
      category: 'Passport',
      name: 'Stolen Passport Replacement',
      description: 'Report and replace your stolen passport.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
      type: ServiceType.online,
      officialLink: 'https://www.passport.gov.et',
      instructionSteps: [
        'File a police report immediately.',
        'Get a copy of the theft report.',
        'Visit INAS portal and report the theft.',
        'Upload police report and Fayda ID.',
        'Pay the replacement and processing fee.',
        'Attend biometric appointment.'
      ],
      requirements: ['Police Theft Report', 'Fayda ID', 'Affidavit', 'Payment Receipt'],
      assistanceFee: 150.0,
    ),
    GeneralService(
      id: 'pass_emergency',
      category: 'Passport',
      name: 'Emergency Travel Document',
      description: 'Get an emergency travel document for urgent travel needs.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
      type: ServiceType.inPerson,
      officialLink: 'https://www.passport.gov.et',
      instructionSteps: [
        'Visit the INAS office in person with proof of emergency.',
        'Bring your Fayda ID and travel documents.',
        'Explain your emergency situation.',
        'Pay the expedited processing fee.',
        'Receive emergency travel document within 24-48 hours.'
      ],
      requirements: ['Fayda ID', 'Proof of Emergency', 'Flight Ticket', 'Expedited Fee'],
      assistanceFee: 200.0,
    ),
    GeneralService(
      id: 'pass_name_correction',
      category: 'Passport',
      name: 'Name Correction',
      description: 'Correct spelling errors or update your name on passport.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
      type: ServiceType.online,
      officialLink: 'https://www.passport.gov.et',
      instructionSteps: [
        'Login to INAS portal.',
        'Select "Name Correction/Update".',
        'Upload supporting documents (court order, marriage certificate).',
        'Enter your Fayda FIN.',
        'Pay the correction fee.',
        'Submit old passport at appointment.'
      ],
      requirements: ['Current Passport', 'Legal Document', 'Fayda ID', 'Court Order/Marriage Certificate'],
      assistanceFee: 130.0,
    ),
    GeneralService(
      id: 'pass_extension',
      category: 'Passport',
      name: 'Passport Validity Extension',
      description: 'Extend your passport validity while abroad.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
      type: ServiceType.online,
      officialLink: 'https://www.passport.gov.et',
      instructionSteps: [
        'Contact the nearest Ethiopian embassy.',
        'Provide your current passport and Fayda ID.',
        'Fill out the extension application form.',
        'Pay the extension fee.',
        'Receive extended passport within 5-7 business days.'
      ],
      requirements: ['Current Passport', 'Fayda ID', 'Proof of Residence Abroad'],
      assistanceFee: 100.0,
    ),
    GeneralService(
      id: 'pass_child',
      category: 'Passport',
      name: 'Child Passport Application',
      description: 'Apply for a passport for children under 18 years.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
      type: ServiceType.online,
      officialLink: 'https://www.passport.gov.et',
      instructionSteps: [
        'Visit INAS portal with parent/guardian.',
        'Provide child\'s birth certificate and Fayda ID.',
        'Submit both parents\' consent forms.',
        'Upload child\'s photo.',
        'Pay the child passport fee.',
        'Attend appointment with the child.'
      ],
      requirements: ['Child Birth Certificate', 'Child Fayda ID', 'Parents Consent', 'Guardian ID'],
      assistanceFee: 120.0,
    ),
    GeneralService(
      id: 'pass_status_check',
      category: 'Passport',
      name: 'Passport Status Tracking',
      description: 'Check the status of your passport application.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
      type: ServiceType.online,
      officialLink: 'https://www.passport.gov.et',
      instructionSteps: [
        'Visit INAS tracking portal.',
        'Enter your application reference number.',
        'Enter your Fayda FIN.',
        'View current status and estimated completion date.',
        'Download receipt if ready for collection.'
      ],
      requirements: ['Application Reference Number', 'Fayda FIN'],
      assistanceFee: 0.0,
    ),
  ];
});

final educationServiceProvider = Provider<List<GeneralService>>((ref) {
  return [
    GeneralService(
      id: 'edu_exam',
      category: 'Education',
      name: 'Grade 12 Exam Registration',
      description: 'Link your Fayda ID to your national exam registration.',
      logo: 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
      type: ServiceType.online,
      officialLink: 'https://eaes.et',
      instructionSteps: [
        'Go to the EAES registration portal.',
        'Select Student Registration.',
        'Enter your school code and Fayda FIN.',
        'Verify your personal details against the NID database.',
        'Confirm and submit.'
      ],
      requirements: ['School Code', 'Fayda ID', 'Grade 11 Results'],
      assistanceFee: 50.0,
    ),
    GeneralService(
      id: 'edu_uni_admission',
      category: 'Education',
      name: 'University Admission Link',
      description: 'Link Fayda ID for university placement and student ID.',
      logo: 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
      type: ServiceType.online,
      officialLink: 'https://www.moe.gov.et',
      instructionSteps: [
        'Register on the Ministry of Education student portal.',
        'Provide your Fayda FIN for identity verification.',
        'Wait for placement notification based on your verified data.'
      ],
      requirements: ['Grade 12 Result', 'Fayda ID'],
      assistanceFee: 80.0,
    ),
    GeneralService(
      id: 'edu_scholarship',
      category: 'Education',
      name: 'Scholarship Application',
      description: 'Apply for government or university scholarships.',
      logo: 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
      type: ServiceType.online,
      officialLink: 'https://www.moe.gov.et',
      instructionSteps: [
        'Visit MoE scholarship portal.',
        'Verify identity with Fayda ID.',
        'Upload academic transcripts.',
        'Submit financial need documents.',
        'Complete application form.',
        'Wait for evaluation results.'
      ],
      requirements: ['Fayda ID', 'Academic Records', 'Financial Documents', 'Recommendation Letters'],
      assistanceFee: 100.0,
    ),
    GeneralService(
      id: 'edu_student_id',
      category: 'Education',
      name: 'Student ID Verification',
      description: 'Verify and link your university student ID with Fayda.',
      logo: 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
      type: ServiceType.online,
      officialLink: 'https://www.moe.gov.et',
      instructionSteps: [
        'Login to your university portal.',
        'Navigate to Student Profile.',
        'Link Fayda FIN to student record.',
        'Upload Fayda ID photo.',
        'Verify biometric data if required.',
        'Receive digital student ID.'
      ],
      requirements: ['Fayda ID', 'University Admission Letter', 'Student Number'],
      assistanceFee: 60.0,
    ),
    GeneralService(
      id: 'edu_transcript',
      category: 'Education',
      name: 'Transcript Request',
      description: 'Request official academic transcripts digitally.',
      logo: 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
      type: ServiceType.online,
      officialLink: 'https://www.moe.gov.et',
      instructionSteps: [
        'Login to MoE student portal.',
        'Verify identity with Fayda ID.',
        'Select transcript type (official/unofficial).',
        'Pay processing fee.',
        'Choose delivery method (digital/physical).',
        'Receive transcript within 5-7 days.'
      ],
      requirements: ['Fayda ID', 'Student ID', 'Payment Receipt'],
      assistanceFee: 70.0,
    ),
    GeneralService(
      id: 'edu_tvet',
      category: 'Education',
      name: 'TVET Enrollment',
      description: 'Enroll in Technical and Vocational Education Training.',
      logo: 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
      type: ServiceType.online,
      officialLink: 'https://www.tvetethiopia.gov.et',
      instructionSteps: [
        'Visit TVET portal.',
        'Select your preferred program.',
        'Verify identity with Fayda ID.',
        'Upload Grade 10 certificate.',
        'Complete enrollment form.',
        'Pay registration fee.'
      ],
      requirements: ['Fayda ID', 'Grade 10 Certificate', 'Birth Certificate'],
      assistanceFee: 90.0,
    ),
    GeneralService(
      id: 'edu_graduate_verify',
      category: 'Education',
      name: 'Graduate Verification',
      description: 'Verify your degree for employers or further studies.',
      logo: 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
      type: ServiceType.online,
      officialLink: 'https://www.moe.gov.et',
      instructionSteps: [
        'Login to MoE verification portal.',
        'Enter your Fayda FIN.',
        'Upload degree certificate.',
        'Submit verification request.',
        'Pay verification fee.',
        'Receive digital verification certificate.'
      ],
      requirements: ['Fayda ID', 'Degree Certificate', 'University Transcript'],
      assistanceFee: 120.0,
    ),
    GeneralService(
      id: 'edu_student_loan',
      category: 'Education',
      name: 'Student Loan Application',
      description: 'Apply for government student loan program.',
      logo: 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
      type: ServiceType.online,
      officialLink: 'https://www.moe.gov.et',
      instructionSteps: [
        'Visit student loan portal.',
        'Verify identity with Fayda ID.',
        'Submit admission letter.',
        'Provide guarantor information.',
        'Upload financial documents.',
        'Sign loan agreement digitally.',
        'Wait for approval.'
      ],
      requirements: ['Fayda ID', 'University Admission', 'Guarantor Details', 'Financial Statements'],
      assistanceFee: 150.0,
    ),
    GeneralService(
      id: 'edu_record_correction',
      category: 'Education',
      name: 'Education Record Correction',
      description: 'Correct errors in your academic records.',
      logo: 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
      type: ServiceType.online,
      officialLink: 'https://www.moe.gov.et',
      instructionSteps: [
        'Login to MoE portal.',
        'Select "Record Correction".',
        'Verify identity with Fayda ID.',
        'Upload supporting documents.',
        'Explain the correction needed.',
        'Submit request for review.',
        'Receive corrected records.'
      ],
      requirements: ['Fayda ID', 'Original Documents', 'Supporting Evidence', 'Affidavit if needed'],
      assistanceFee: 100.0,
    ),
    GeneralService(
      id: 'edu_grade10_cert',
      category: 'Education',
      name: 'Grade 10 Certificate Request',
      description: 'Request duplicate or digital Grade 10 certificate.',
      logo: 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
      type: ServiceType.online,
      officialLink: 'https://www.moe.gov.et',
      instructionSteps: [
        'Visit MoE certificate portal.',
        'Verify with Fayda ID.',
        'Enter school details.',
        'Pay certificate fee.',
        'Choose delivery method.',
        'Receive certificate within 10 days.'
      ],
      requirements: ['Fayda ID', 'School Name', 'Year of Completion'],
      assistanceFee: 50.0,
    ),
  ];
});

final businessServiceProvider = Provider<List<GeneralService>>((ref) {
  return [
    GeneralService(
      id: 'biz_tin',
      category: 'Business',
      name: 'TIN Registration',
      description: 'Get your Taxpayer Identification Number using Fayda.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
      type: ServiceType.online,
      officialLink: 'https://etrade.gov.et',
      instructionSteps: [
        'Access the e-Trade portal.',
        'Select "New TIN Registration".',
        'Use Fayda ID for electronic signature and verification.',
        'Fill in business details.',
        'Submit for digital certificate issuance.'
      ],
      requirements: ['Fayda ID', 'Business Address', 'Phone Number'],
      assistanceFee: 150.0,
    ),
    GeneralService(
      id: 'biz_license_new',
      category: 'Business',
      name: 'New Business License',
      description: 'Apply for a new business license using your Fayda ID.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
      type: ServiceType.online,
      officialLink: 'https://etrade.gov.et',
      instructionSteps: [
        'Visit Ministry of Trade portal.',
        'Select "New Business License".',
        'Verify identity with Fayda ID.',
        'Upload business plan and documents.',
        'Pay license fee via Telebirr.',
        'Receive digital license certificate.'
      ],
      requirements: ['Fayda ID', 'TIN', 'Business Plan', 'Rental Agreement', 'Payment Receipt'],
      assistanceFee: 250.0,
    ),
    GeneralService(
      id: 'biz_license_renew',
      category: 'Business',
      name: 'Business License Renewal',
      description: 'Renew your trade license with Fayda verification.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
      type: ServiceType.online,
      officialLink: 'https://etrade.gov.et',
      instructionSteps: [
        'Login to Ministry of Trade portal.',
        'Link your Fayda ID to your existing profile.',
        'Pay renewal fees via Telebirr.',
        'Download your renewed digital license.'
      ],
      requirements: ['Existing License', 'Fayda ID', 'Tax Clearance'],
      assistanceFee: 200.0,
    ),
    GeneralService(
      id: 'biz_trade_name',
      category: 'Business',
      name: 'Trade Name Reservation',
      description: 'Reserve your business name before registration.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
      type: ServiceType.online,
      officialLink: 'https://etrade.gov.et',
      instructionSteps: [
        'Access e-Trade portal.',
        'Search for name availability.',
        'Submit 3 preferred names.',
        'Verify with Fayda ID.',
        'Pay reservation fee.',
        'Receive approval within 3 business days.'
      ],
      requirements: ['Fayda ID', 'Proposed Business Names', 'Payment'],
      assistanceFee: 100.0,
    ),
    GeneralService(
      id: 'biz_vat',
      category: 'Business',
      name: 'VAT Registration',
      description: 'Register for Value Added Tax (VAT) certificate.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
      type: ServiceType.online,
      officialLink: 'https://etrade.gov.et',
      instructionSteps: [
        'Login to Ethiopian Revenue portal.',
        'Select "VAT Registration".',
        'Link your TIN and Fayda ID.',
        'Upload business license.',
        'Submit financial documents.',
        'Receive VAT certificate digitally.'
      ],
      requirements: ['TIN', 'Business License', 'Fayda ID', 'Financial Statements'],
      assistanceFee: 180.0,
    ),
    GeneralService(
      id: 'biz_import_export',
      category: 'Business',
      name: 'Import/Export License',
      description: 'Get license for international trade operations.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
      type: ServiceType.online,
      officialLink: 'https://etrade.gov.et',
      instructionSteps: [
        'Visit Ministry of Trade portal.',
        'Select "Import/Export License".',
        'Verify identity with Fayda ID.',
        'Upload company documents.',
        'Pay license fee.',
        'Attend inspection if required.'
      ],
      requirements: ['Business License', 'TIN', 'Fayda ID', 'Bank Statement', 'Warehouse Proof'],
      assistanceFee: 300.0,
    ),
    GeneralService(
      id: 'biz_company_reg',
      category: 'Business',
      name: 'Company Registration',
      description: 'Register a new company (PLC, Share Company, etc.).',
      logo: 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
      type: ServiceType.online,
      officialLink: 'https://etrade.gov.et',
      instructionSteps: [
        'Prepare company memorandum and articles.',
        'Visit e-Trade portal.',
        'Submit shareholder details with Fayda IDs.',
        'Upload all required documents.',
        'Pay registration fee.',
        'Receive company certificate.'
      ],
      requirements: ['Shareholders Fayda IDs', 'Memorandum', 'Articles of Association', 'Capital Proof'],
      assistanceFee: 500.0,
    ),
    GeneralService(
      id: 'biz_tax_clearance',
      category: 'Business',
      name: 'Tax Clearance Certificate',
      description: 'Get tax clearance for license renewal or tenders.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
      type: ServiceType.online,
      officialLink: 'https://www.mor.gov.et',
      instructionSteps: [
        'Login to Ministry of Revenue portal.',
        'Verify identity with Fayda ID.',
        'Submit tax payment receipts.',
        'Request clearance certificate.',
        'Download digital certificate.'
      ],
      requirements: ['TIN', 'Fayda ID', 'Tax Payment Receipts', 'Business License'],
      assistanceFee: 120.0,
    ),
    GeneralService(
      id: 'biz_closure',
      category: 'Business',
      name: 'Business Closure/Cancellation',
      description: 'Officially close and deregister your business.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
      type: ServiceType.online,
      officialLink: 'https://etrade.gov.et',
      instructionSteps: [
        'Login to e-Trade portal.',
        'Select "Business Closure".',
        'Verify with Fayda ID.',
        'Submit tax clearance.',
        'Upload closure documents.',
        'Receive closure certificate.'
      ],
      requirements: ['Business License', 'Tax Clearance', 'Fayda ID', 'Final Financial Statement'],
      assistanceFee: 150.0,
    ),
    GeneralService(
      id: 'biz_name_change',
      category: 'Business',
      name: 'Business Name Change',
      description: 'Update or change your registered business name.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
      type: ServiceType.online,
      officialLink: 'https://etrade.gov.et',
      instructionSteps: [
        'Check new name availability.',
        'Login to Ministry of Trade portal.',
        'Submit name change request.',
        'Upload supporting documents.',
        'Verify with Fayda ID.',
        'Pay amendment fee.',
        'Receive updated license.'
      ],
      requirements: ['Current License', 'Fayda ID', 'Board Resolution', 'New Name Reservation'],
      assistanceFee: 180.0,
    ),
  ];
});

final publicServiceServiceProvider = Provider<List<GeneralService>>((ref) {
  return [
    GeneralService(
      id: 'pub_driver_renew',
      category: 'Public Service',
      name: 'Driver License Renewal',
      description: 'Renew your driving license digitally using Fayda identity.',
      logo: 'https://cdn-icons-png.flaticon.com/512/2554/2554930.png',
      type: ServiceType.online,
      officialLink: 'https://www.transport.gov.et',
      instructionSteps: [
        'Go to the Transport Authority digital portal.',
        'Validate your identity with Fayda ID.',
        'Submit medical certificate digital copy.',
        'Pay the renewal fee.',
        'Pick up your license or request delivery.'
      ],
      requirements: ['Expired License', 'Medical Certificate', 'Fayda ID'],
      assistanceFee: 50.0,
    ),
    GeneralService(
      id: 'pub_driver_new',
      category: 'Public Service',
      name: 'New Driver License',
      description: 'Apply for a new driving license.',
      logo: 'https://cdn-icons-png.flaticon.com/512/2554/2554930.png',
      type: ServiceType.inPerson,
      officialLink: 'https://www.transport.gov.et',
      instructionSteps: [
        'Complete driving school training.',
        'Pass theoretical and practical exams.',
        'Visit Transport Authority office.',
        'Verify identity with Fayda ID.',
        'Submit medical certificate.',
        'Pay license fee.',
        'Receive license within 7 days.'
      ],
      requirements: ['Fayda ID', 'Driving School Certificate', 'Medical Certificate', 'Exam Results'],
      assistanceFee: 100.0,
    ),
    GeneralService(
      id: 'pub_birth_cert',
      category: 'Vital Events',
      name: 'Birth Certificate Registration',
      description: 'Register and link birth certificate to Fayda.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3209/3209224.png',
      type: ServiceType.inPerson,
      officialLink: 'https://www.vitalevents.gov.et',
      instructionSteps: [
        'Visit your local Woreda Vital Events office.',
        'Present your physical Fayda ID card.',
        'Provide your registered birth certificate number.',
        'Verify biometrics on the agent device.',
        'Receive digital certificate link.'
      ],
      requirements: ['Physical ID', 'Birth Certificate', 'Woreda Appointment'],
      assistanceFee: 150.0,
    ),
    GeneralService(
      id: 'pub_marriage_cert',
      category: 'Vital Events',
      name: 'Marriage Certificate',
      description: 'Register marriage and get official certificate.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3209/3209224.png',
      type: ServiceType.inPerson,
      officialLink: 'https://www.vitalevents.gov.et',
      instructionSteps: [
        'Visit Woreda office with spouse.',
        'Present both Fayda IDs.',
        'Provide witness information.',
        'Sign marriage register.',
        'Pay registration fee.',
        'Receive marriage certificate.'
      ],
      requirements: ['Both Fayda IDs', 'Witnesses', 'Birth Certificates'],
      assistanceFee: 80.0,
    ),
    GeneralService(
      id: 'pub_death_cert',
      category: 'Vital Events',
      name: 'Death Certificate',
      description: 'Register death and obtain official certificate.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3209/3209224.png',
      type: ServiceType.inPerson,
      officialLink: 'https://www.vitalevents.gov.et',
      instructionSteps: [
        'Visit Woreda office with medical report.',
        'Present deceased Fayda ID.',
        'Provide family member Fayda ID.',
        'Submit hospital death report.',
        'Complete registration form.',
        'Receive death certificate.'
      ],
      requirements: ['Deceased Fayda ID', 'Medical Report', 'Family Member ID'],
      assistanceFee: 60.0,
    ),
    GeneralService(
      id: 'pub_pension',
      category: 'Social Security',
      name: 'Pensioner Verification',
      description: 'Annual proof-of-life verification for POESSA pensioners.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
      type: ServiceType.inPerson,
      officialLink: 'https://www.poessa.gov.et',
      instructionSteps: [
        'Visit the nearest POESSA office or partner bank.',
        'Bring your Pensioner Book and Fayda ID.',
        'Scan your fingerprints to verify identity.',
        'Update your contact information in the system.'
      ],
      requirements: ['Pensioner Book', 'Fayda ID', 'Fingerprint Scan'],
      assistanceFee: 30.0,
    ),
    GeneralService(
      id: 'pub_police_clearance',
      category: 'Public Service',
      name: 'Police Clearance Certificate',
      description: 'Get police clearance for visa or employment.',
      logo: 'https://cdn-icons-png.flaticon.com/512/2554/2554930.png',
      type: ServiceType.online,
      officialLink: 'https://www.police.gov.et',
      instructionSteps: [
        'Visit police clearance portal.',
        'Verify identity with Fayda ID.',
        'Submit fingerprints at police station.',
        'Pay clearance fee.',
        'Receive certificate within 5-10 days.'
      ],
      requirements: ['Fayda ID', 'Fingerprints', 'Payment Receipt'],
      assistanceFee: 100.0,
    ),
    GeneralService(
      id: 'pub_health_insurance',
      category: 'Social Security',
      name: 'Health Insurance Registration',
      description: 'Register for community-based health insurance.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
      type: ServiceType.online,
      officialLink: 'https://www.fmoh.gov.et',
      instructionSteps: [
        'Visit health insurance portal.',
        'Verify with Fayda ID.',
        'Select insurance plan.',
        'Add family members.',
        'Pay premium.',
        'Receive insurance card.'
      ],
      requirements: ['Fayda ID', 'Family Members IDs', 'Payment'],
      assistanceFee: 70.0,
    ),
  ];
});

final telecomServiceProvider = Provider<List<GeneralService>>((ref) {
  return [
    GeneralService(
      id: 'tel_sim_reg',
      category: 'Telecom',
      name: 'SIM Card Registration',
      description: 'Link your Ethio Telecom or Safaricom SIM to Fayda.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3415/3415077.png',
      type: ServiceType.online,
      officialLink: 'https://www.ethiotelecom.et',
      instructionSteps: [
        'Dial *804# or visit mobile operator app.',
        'Enter your 12-digit Fayda FIN.',
        'Upload a photo of your Fayda card if requested.',
        'Receive confirmation SMS.'
      ],
      requirements: ['Active SIM', 'Fayda ID', '12-digit FIN'],
      assistanceFee: 20.0,
    ),
    GeneralService(
      id: 'tel_new_sim',
      category: 'Telecom',
      name: 'New SIM Card Purchase',
      description: 'Buy a new SIM card with Fayda ID verification.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3415/3415077.png',
      type: ServiceType.inPerson,
      officialLink: 'https://www.ethiotelecom.et',
      instructionSteps: [
        'Visit Ethio Telecom or Safaricom shop.',
        'Present your Fayda ID.',
        'Choose phone number.',
        'Pay SIM card fee.',
        'Activate SIM immediately.'
      ],
      requirements: ['Fayda ID', 'Payment'],
      assistanceFee: 30.0,
    ),
    GeneralService(
      id: 'tel_number_portability',
      category: 'Telecom',
      name: 'Number Portability',
      description: 'Keep your number when switching operators.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3415/3415077.png',
      type: ServiceType.online,
      officialLink: 'https://www.ethiotelecom.et',
      instructionSteps: [
        'Visit new operator shop.',
        'Request number portability.',
        'Verify with Fayda ID.',
        'Pay portability fee.',
        'Wait 24-48 hours for activation.'
      ],
      requirements: ['Fayda ID', 'Current SIM', 'Payment'],
      assistanceFee: 50.0,
    ),
    GeneralService(
      id: 'tel_lost_sim',
      category: 'Telecom',
      name: 'Lost SIM Replacement',
      description: 'Replace lost or stolen SIM card.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3415/3415077.png',
      type: ServiceType.inPerson,
      officialLink: 'https://www.ethiotelecom.et',
      instructionSteps: [
        'Visit operator shop immediately.',
        'Report SIM loss.',
        'Verify identity with Fayda ID.',
        'Pay replacement fee.',
        'Receive new SIM with same number.'
      ],
      requirements: ['Fayda ID', 'Phone Number', 'Payment'],
      assistanceFee: 40.0,
    ),
    GeneralService(
      id: 'tel_data_plan',
      category: 'Telecom',
      name: 'Data Plan Subscription',
      description: 'Subscribe to internet data packages.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3415/3415077.png',
      type: ServiceType.online,
      officialLink: 'https://www.ethiotelecom.et',
      instructionSteps: [
        'Dial *999# for Ethio Telecom.',
        'Select data package.',
        'Confirm subscription.',
        'Receive activation SMS.'
      ],
      requirements: ['Active SIM', 'Sufficient Balance'],
      assistanceFee: 0.0,
    ),
    GeneralService(
      id: 'tel_mobile_money',
      category: 'Telecom',
      name: 'Mobile Money Registration',
      description: 'Register for Telebirr or M-PESA services.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3415/3415077.png',
      type: ServiceType.online,
      officialLink: 'https://www.telebirr.com',
      instructionSteps: [
        'Download Telebirr or M-PESA app.',
        'Enter your phone number.',
        'Verify with Fayda ID.',
        'Create PIN.',
        'Complete registration.'
      ],
      requirements: ['Fayda ID', 'Active SIM', 'Smartphone'],
      assistanceFee: 25.0,
    ),
    GeneralService(
      id: 'tel_postpaid',
      category: 'Telecom',
      name: 'Postpaid Plan Registration',
      description: 'Switch to postpaid billing plan.',
      logo: 'https://cdn-icons-png.flaticon.com/512/3415/3415077.png',
      type: ServiceType.inPerson,
      officialLink: 'https://www.ethiotelecom.et',
      instructionSteps: [
        'Visit operator shop.',
        'Verify identity with Fayda ID.',
        'Choose postpaid plan.',
        'Provide billing address.',
        'Sign contract.',
        'Activate postpaid service.'
      ],
      requirements: ['Fayda ID', 'Proof of Address', 'Employment Letter'],
      assistanceFee: 80.0,
    ),
  ];
});
