import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/foundation.dart';
import '../models/service_model.dart';

class DatabaseSeeder {
  static Future<void> seedServices() async {
    final database = FirebaseDatabase.instanceFor(
      app: Firebase.app(),
      databaseURL: 'https://fayda-connect-default-rtdb.firebaseio.com',
    );
    final dbRef = database.ref('services');

    final services = [
      // Passport Services
      {
        'id': 'pass_new',
        'category': 'Passport',
        'name': 'New Passport Application',
        'description': 'Apply for your first electronic passport using Fayda ID.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
        'type': 'online',
        'officialLink': 'https://www.mfa.gov.et',
        'instructionSteps': [
          'Get your 12-digit FIN from your Fayda ID card.',
          'Visit the official INAS portal.',
          'Select "New Passport" and enter your FIN.',
          'Choose your appointment date and office location.',
          'Complete Official Requirements via Telebirr or CBE Birr.',
          'Print your appointment slip.'
        ],
        'requirements': ['Fayda FIN', 'Birth Certificate', 'Telebirr/CBE Birr', 'Appointment Slip'],
        'priorityPoints': 100.0,
      },
      {
        'id': 'pass_renew',
        'category': 'Passport',
        'name': 'Passport Renewal',
        'description': 'Renew your expiring passport with your digital ID.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
        'type': 'online',
        'officialLink': 'https://www.mfa.gov.et',
        'instructionSteps': [
          'Login to the INAS portal.',
          'Enter your old passport number and Fayda FIN.',
          'Upload a digital photo if required.',
          'Complete renewal requirements.',
          'Schedule your biometric data collection.'
        ],
        'requirements': ['Old Passport', 'Fayda ID', 'Digital Photo'],
        'priorityPoints': 100.0,
      },
      {
        'id': 'pass_lost',
        'category': 'Passport',
        'name': 'Lost Passport Replacement',
        'description': 'Replace your lost or stolen passport using Fayda verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
        'type': 'inPerson',
        'officialLink': 'https://www.mfa.gov.et',
        'instructionSteps': [
          'Report lost passport to local police.',
          'Visit immigration office with police report.',
          'Verify identity with Fayda ID.',
          'Complete replacement application.',
          'Pay replacement fees and schedule pickup.'
        ],
        'requirements': ['Police Report', 'Fayda ID', 'Passport Photos', 'Replacement Fee'],
        'priorityPoints': 150.0,
      },
      {
        'id': 'pass_emergency',
        'category': 'Passport',
        'name': 'Emergency Passport',
        'description': 'Get emergency passport for urgent travel using Fayda verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
        'type': 'inPerson',
        'officialLink': 'https://www.mfa.gov.et',
        'instructionSteps': [
          'Visit immigration office with proof of emergency.',
          'Verify identity with Fayda ID.',
          'Submit emergency travel documents.',
          'Pay expedited service fees.',
          'Receive emergency passport same day.'
        ],
        'requirements': ['Emergency Proof', 'Fayda ID', 'Travel Documents', 'Expedited Fee'],
        'priorityPoints': 200.0,
      },
      {
        'id': 'pass_damaged',
        'category': 'Passport',
        'name': 'Damaged Passport Replacement',
        'description': 'Replace damaged or mutilated passport using Fayda verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
        'type': 'inPerson',
        'officialLink': 'https://www.mfa.gov.et',
        'instructionSteps': [
          'Visit immigration office with damaged passport.',
          'Submit damage report and explanation.',
          'Verify identity with Fayda ID.',
          'Complete replacement application.',
          'Pay replacement fees and schedule pickup.'
        ],
        'requirements': ['Damaged Passport', 'Fayda ID', 'Damage Report', 'Replacement Fee'],
        'priorityPoints': 120.0,
      },
      {
        'id': 'pass_name_change',
        'category': 'Passport',
        'name': 'Passport Name Change',
        'description': 'Update passport name due to marriage, divorce, or legal name change.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
        'type': 'inPerson',
        'officialLink': 'https://www.mfa.gov.et',
        'instructionSteps': [
          'Visit immigration office with current passport.',
          'Submit legal name change documents.',
          'Verify identity with updated Fayda ID.',
          'Complete name change application.',
          'Pay processing fees and receive updated passport.'
        ],
        'requirements': ['Current Passport', 'Fayda ID', 'Legal Name Change Document', 'Processing Fee'],
        'priorityPoints': 130.0,
      },
      {
        'id': 'pass_child',
        'category': 'Passport',
        'name': 'Child Passport Application',
        'description': 'Apply for passport for minors under 18 using parental Fayda verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
        'type': 'inPerson',
        'officialLink': 'https://www.mfa.gov.et',
        'instructionSteps': [
          'Visit immigration office with child and parents.',
          'Verify parental identity with Fayda IDs.',
          'Submit child birth certificate and photos.',
          'Complete child passport application.',
          'Pay fees and schedule passport collection.'
        ],
        'requirements': ['Parent Fayda IDs', 'Child Birth Certificate', 'Child Photos', 'Application Fee'],
        'priorityPoints': 90.0,
      },
      {
        'id': 'pass_pages_add',
        'category': 'Passport',
        'name': 'Additional Passport Pages',
        'description': 'Add extra pages to valid passport for frequent travelers.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
        'type': 'inPerson',
        'officialLink': 'https://www.mfa.gov.et',
        'instructionSteps': [
          'Visit immigration office with current passport.',
          'Submit request for additional pages.',
          'Verify identity with Fayda ID.',
          'Provide proof of frequent travel.',
          'Pay additional pages fee and receive updated passport.'
        ],
        'requirements': ['Current Passport', 'Fayda ID', 'Travel Proof', 'Additional Pages Fee'],
        'priorityPoints': 80.0,
      },
      {
        'id': 'pass_correction',
        'category': 'Passport',
        'name': 'Passport Information Correction',
        'description': 'Correct errors in passport information using Fayda verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
        'type': 'inPerson',
        'officialLink': 'https://www.mfa.gov.et',
        'instructionSteps': [
          'Visit immigration office with error-containing passport.',
          'Submit correction request with supporting documents.',
          'Verify identity with Fayda ID.',
          'Complete correction application form.',
          'Pay correction fee and receive corrected passport.'
        ],
        'requirements': ['Passport with Error', 'Fayda ID', 'Supporting Documents', 'Correction Fee'],
        'priorityPoints': 70.0,
      },
      {
        'id': 'pass_second_copy',
        'category': 'Passport',
        'name': 'Second Passport Application',
        'description': 'Apply for second valid passport for business or visa purposes.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
        'type': 'inPerson',
        'officialLink': 'https://www.mfa.gov.et',
        'instructionSteps': [
          'Visit immigration office with current passport.',
          'Submit justification for second passport.',
          'Verify identity with Fayda ID.',
          'Complete second passport application.',
          'Pay second passport fees and await approval.'
        ],
        'requirements': ['Current Passport', 'Fayda ID', 'Justification Letter', 'Second Passport Fee'],
        'priorityPoints': 180.0,
      },
      {
        'id': 'pass_biometric_update',
        'category': 'Passport',
        'name': 'Biometric Data Update',
        'description': 'Update biometric information for passport using Fayda verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
        'type': 'inPerson',
        'officialLink': 'https://www.mfa.gov.et',
        'instructionSteps': [
          'Visit immigration office for biometric update.',
          'Verify identity with current Fayda ID.',
          'Provide reason for biometric update.',
          'Complete new biometric capture.',
          'Receive updated passport with new biometrics.'
        ],
        'requirements': ['Current Passport', 'Fayda ID', 'Update Reason', 'Update Fee'],
        'priorityPoints': 100.0,
      },
      {
        'id': 'pass_diplomatic',
        'category': 'Passport',
        'name': 'Diplomatic Passport Application',
        'description': 'Apply for diplomatic passport for government officials.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
        'type': 'inPerson',
        'officialLink': 'https://www.mfa.gov.et',
        'instructionSteps': [
          'Submit diplomatic passport application through ministry.',
          'Provide government appointment letter.',
          'Verify identity with Fayda ID.',
          'Complete diplomatic clearance process.',
          'Receive diplomatic passport upon approval.'
        ],
        'requirements': ['Fayda ID', 'Government Appointment', 'Ministry Clearance', 'Diplomatic Fee'],
        'priorityPoints': 250.0,
      },
      {
        'id': 'pass_service',
        'category': 'Passport',
        'name': 'Service Passport Application',
        'description': 'Apply for service passport for government employees on official duty.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
        'type': 'inPerson',
        'officialLink': 'https://www.mfa.gov.et',
        'instructionSteps': [
          'Submit service passport application through employer.',
          'Provide official duty assignment letter.',
          'Verify identity with Fayda ID.',
          'Complete government clearance process.',
          'Receive service passport upon approval.'
        ],
        'requirements': ['Fayda ID', 'Duty Assignment', 'Employer Letter', 'Service Fee'],
        'priorityPoints': 220.0,
      },
      {
        'id': 'pass_expedited',
        'category': 'Passport',
        'name': 'Expedited Passport Service',
        'description': 'Get expedited passport processing for urgent travel needs.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3201/3201111.png',
        'type': 'inPerson',
        'officialLink': 'https://www.mfa.gov.et',
        'instructionSteps': [
          'Visit immigration office with urgent travel proof.',
          'Submit expedited service request.',
          'Verify identity with Fayda ID.',
          'Pay expedited processing fees.',
          'Receive passport within 24-48 hours.'
        ],
        'requirements': ['Fayda ID', 'Urgent Travel Proof', 'Expedited Fee', 'Supporting Documents'],
        'priorityPoints': 190.0,
      },
      // ... adding more for the other categories (shortened for the seeder utility example, 
      // but I will include all categories to ensure they are migrated)
      {
        'id': 'edu_exam',
        'category': 'Education',
        'name': 'Grade 12 Exam Registration',
        'description': 'Link your Fayda ID to your national exam registration.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'online',
        'officialLink': 'https://eaes.et',
        'instructionSteps': [
          'Go to the EAES registration portal.',
          'Select Student Registration.',
          'Enter your school code and Fayda FIN.',
          'Verify your personal details against the NID database.',
          'Confirm and submit.'
        ],
        'requirements': ['School Code', 'Fayda ID', 'Grade 11 Results'],
        'priorityPoints': 50.0,
      },
      {
        'id': 'edu_university',
        'category': 'Education',
        'name': 'University Admission',
        'description': 'Apply to Ethiopian universities using Fayda digital identity.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'online',
        'officialLink': 'https://www.hec.gov.et',
        'instructionSteps': [
          'Access the Higher Education admission portal.',
          'Select your preferred universities and programs.',
          'Verify identity with Fayda FIN.',
          'Upload Grade 12 exam results.',
          'Submit application and track status.'
        ],
        'requirements': ['Fayda ID', 'Grade 12 Results', 'Application Fee'],
        'priorityPoints': 80.0,
      },
      {
        'id': 'edu_scholarship',
        'category': 'Education',
        'name': 'Government Scholarship',
        'description': 'Apply for government scholarships using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'online',
        'officialLink': 'https://www.moe.gov.et',
        'instructionSteps': [
          'Visit Ministry of Education scholarship portal.',
          'Create profile with Fayda ID verification.',
          'Select scholarship programs.',
          'Upload academic documents and proof of need.',
          'Submit application before deadline.'
        ],
        'requirements': ['Fayda ID', 'Academic Transcripts', 'Proof of Need', 'Recommendation Letters'],
        'priorityPoints': 120.0,
      },
      {
        'id': 'edu_student_loan',
        'category': 'Education',
        'name': 'Student Loan Application',
        'description': 'Apply for student loans through Commercial Bank of Ethiopia.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'online',
        'officialLink': 'https://www.combanketh.et',
        'instructionSteps': [
          'Access CBE student loan portal.',
          'Verify identity with Fayda ID.',
          'Upload university admission letter.',
          'Provide guarantor information.',
          'Submit loan application and await approval.'
        ],
        'requirements': ['Fayda ID', 'Admission Letter', 'Guarantor Details', 'Bank Account'],
        'priorityPoints': 90.0,
      },
      {
        'id': 'bank_cbe_fayda_sync',
        'category': 'Banking & Finance',
        'name': 'CBE Fayda ID Sync',
        'description': 'Sync your Fayda ID with Commercial Bank of Ethiopia accounts.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'online',
        'officialLink': 'https://cbefayda.cbe.com.et',
        'instructionSteps': [
          'Visit CBE Fayda portal.',
          'Select Fayda ID synchronization.',
          'Enter your CBE account number.',
          'Verify with OTP sent to your phone.',
          'Enter your 12-digit Fayda FIN.',
          'Submit and wait for confirmation.'
        ],
        'requirements': ['CBE Account', 'Fayda ID', 'Active Phone Number', 'OTP Access'],
        'priorityPoints': 100.0,
      },
      {
        'id': 'bank_dashen_fayda',
        'category': 'Banking & Finance',
        'name': 'Dashen Bank Fayda Integration',
        'description': 'Link Fayda ID with Dashen Bank digital banking services.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'appBased',
        'officialLink': 'https://www.dashenbank.com',
        'instructionSteps': [
          'Download Dashen Bank mobile app.',
          'Navigate to Fayda integration section.',
          'Verify identity with Fayda ID.',
          'Link your bank accounts.',
          'Start using enhanced banking features.'
        ],
        'requirements': ['Fayda ID', 'Dashen Bank Account', 'Smartphone', 'Mobile App'],
        'priorityPoints': 95.0,
      },
      {
        'id': 'bank_awash_fayda',
        'category': 'Banking & Finance',
        'name': 'Awash Bank Fayda Services',
        'description': 'Access Awash Bank services using Fayda digital identity.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'online',
        'officialLink': 'https://www.awashbank.com',
        'instructionSteps': [
          'Visit Awash Bank online banking portal.',
          'Select Fayda ID verification option.',
          'Enter your Fayda FIN for verification.',
          'Link your bank accounts.',
          'Access enhanced banking services.'
        ],
        'requirements': ['Fayda ID', 'Awash Bank Account', 'Internet Access'],
        'priorityPoints': 90.0,
      },
      {
        'id': 'bank_wegagen_fayda',
        'category': 'Banking & Finance',
        'name': 'Wegagen Bank Fayda Integration',
        'description': 'Connect Fayda ID with Wegagen Bank digital services.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'online',
        'officialLink': 'https://www.wegagenbanksc.com',
        'instructionSteps': [
          'Access Wegagen Bank online platform.',
          'Choose Fayda ID integration.',
          'Verify with Fayda credentials.',
          'Complete account linking process.',
          'Enjoy integrated banking services.'
        ],
        'requirements': ['Fayda ID', 'Wegagen Bank Account', 'Online Banking Access'],
        'priorityPoints': 85.0,
      },
      {
        'id': 'bank_coop_fayda',
        'category': 'Banking & Finance',
        'name': 'Cooperative Bank of Oromia Fayda',
        'description': 'Link Fayda ID with Cooperative Bank of Oromia services.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'appBased',
        'officialLink': 'https://www.cobbank.com.et',
        'instructionSteps': [
          'Download CBO mobile banking app.',
          'Select Fayda ID integration feature.',
          'Verify identity using Fayda FIN.',
          'Link your bank accounts securely.',
          'Access enhanced banking features.'
        ],
        'requirements': ['Fayda ID', 'CBO Account', 'Smartphone', 'Mobile App'],
        'priorityPoints': 88.0,
      },
      {
        'id': 'bank_bunna_fayda',
        'category': 'Banking & Finance',
        'name': 'Bunna International Bank Fayda',
        'description': 'Access Bunna Bank services with Fayda digital identity.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'online',
        'officialLink': 'https://www.bunnabank.com',
        'instructionSteps': [
          'Visit Bunna Bank online banking.',
          'Select Fayda ID verification.',
          'Enter your Fayda FIN.',
          'Complete account verification.',
          'Start using integrated services.'
        ],
        'requirements': ['Fayda ID', 'Bunna Bank Account', 'Online Banking Credentials'],
        'priorityPoints': 82.0,
      },
      {
        'id': 'bank_zemen_fayda',
        'category': 'Banking & Finance',
        'name': 'Zemen Bank Digital Banking',
        'description': 'Open Zemen Bank account using Fayda digital identity.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'appBased',
        'officialLink': 'https://www.zemenbank.com',
        'instructionSteps': [
          'Download Zemen Bank mobile app.',
          'Choose account opening with Fayda.',
          'Verify identity with Fayda ID.',
          'Complete digital account opening.',
          'Start banking immediately.'
        ],
        'requirements': ['Fayda ID', 'Smartphone', 'Mobile App', 'Initial Deposit'],
        'priorityPoints': 92.0,
      },
      {
        'id': 'bank_abyssinia_fayda',
        'category': 'Banking & Finance',
        'name': 'Bank of Abyssinia Fayda Integration',
        'description': 'Link Fayda ID with Bank of Abyssinia digital banking services.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'online',
        'officialLink': 'https://www.bankofabyssinia.com',
        'instructionSteps': [
          'Visit Bank of Abyssinia online banking portal.',
          'Select Fayda ID integration option.',
          'Enter your Fayda FIN for verification.',
          'Link your bank accounts securely.',
          'Access enhanced banking features.'
        ],
        'requirements': ['Fayda ID', 'Bank of Abyssinia Account', 'Online Banking Access'],
        'priorityPoints': 93.0,
      },
      {
        'id': 'edu_grade8',
        'category': 'Education',
        'name': 'Grade 8 Exam Registration',
        'description': 'Register for national Grade 8 examinations using Fayda ID.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'online',
        'officialLink': 'https://eaes.et',
        'instructionSteps': [
          'Visit EAES Grade 8 registration portal.',
          'Enter school code and student Fayda FIN.',
          'Verify student information and school details.',
          'Upload recent photograph and school records.',
          'Pay registration fees and receive confirmation.'
        ],
        'requirements': ['Fayda ID', 'School Code', 'Grade 7 Results', 'Registration Fee'],
        'priorityPoints': 40.0,
      },
      {
        'id': 'edu_grade10',
        'category': 'Education',
        'name': 'Grade 10 Exam Registration',
        'description': 'Register for national Grade 10 examinations using digital identity.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'online',
        'officialLink': 'https://eaes.et',
        'instructionSteps': [
          'Access EAES Grade 10 registration system.',
          'Enter school details and student Fayda FIN.',
          'Verify personal information against NID database.',
          'Upload required documents and photographs.',
          'Complete registration and print admission card.'
        ],
        'requirements': ['Fayda ID', 'School Code', 'Grade 9 Results', 'Passport Photos'],
        'priorityPoints': 45.0,
      },
      {
        'id': 'edu_teacher_license',
        'category': 'Education',
        'name': 'Teacher License Renewal',
        'description': 'Renew professional teaching license using Fayda verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'online',
        'officialLink': 'https://www.moe.gov.et',
        'instructionSteps': [
          'Visit Ministry of Education teacher portal.',
          'Login with Fayda ID and teacher registration number.',
          'Upload professional development certificates.',
          'Submit renewal application and fees.',
          'Receive renewed teaching license.'
        ],
        'requirements': ['Fayda ID', 'Teacher License', 'Development Certificates', 'Renewal Fee'],
        'priorityPoints': 70.0,
      },
      {
        'id': 'edu_school_transfer',
        'category': 'Education',
        'name': 'School Transfer Request',
        'description': 'Apply for student school transfer using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'online',
        'officialLink': 'https://www.moe.gov.et',
        'instructionSteps': [
          'Access regional education bureau transfer portal.',
          'Verify student identity with Fayda ID.',
          'Select current and desired schools.',
          'Upload transfer reason and supporting documents.',
          'Submit request and track approval status.'
        ],
        'requirements': ['Fayda ID', 'Transfer Letter', 'School Records', 'Reason Document'],
        'priorityPoints': 60.0,
      },
      {
        'id': 'edu_certificate',
        'category': 'Education',
        'name': 'Academic Certificate Verification',
        'description': 'Verify academic certificates for employment or further studies.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'online',
        'officialLink': 'https://www.moe.gov.et',
        'instructionSteps': [
          'Visit Ministry of Education verification portal.',
          'Request certificate verification with Fayda ID.',
          'Upload certificate copies for verification.',
          'Pay verification fees online.',
          'Receive verified certificate confirmation.'
        ],
        'requirements': ['Fayda ID', 'Certificate Copies', 'Verification Fee'],
        'priorityPoints': 35.0,
      },
      {
        'id': 'edu_equivalence',
        'category': 'Education',
        'name': 'Foreign Degree Equivalence',
        'description': 'Get equivalence for foreign academic qualifications.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2997/2997313.png',
        'type': 'online',
        'officialLink': 'https://www.hec.gov.et',
        'instructionSteps': [
          'Access HERQA equivalence application portal.',
          'Create profile with Fayda ID verification.',
          'Upload foreign degree documents and transcripts.',
          'Submit translation and authentication documents.',
          'Pay fees and await equivalence assessment.'
        ],
        'requirements': ['Fayda ID', 'Foreign Degree', 'Transcripts', 'Translation Documents'],
        'priorityPoints': 110.0,
      },
      {
        'id': 'biz_tin',
        'category': 'Business',
        'name': 'TIN Registration',
        'description': 'Get your Taxpayer Identification Number using Fayda.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
        'type': 'online',
        'officialLink': 'https://etrade.gov.et',
        'instructionSteps': [
          'Access the e-Trade portal.',
          'Select "New TIN Registration".',
          'Use Fayda ID for electronic signature and verification.',
          'Fill in business details.',
          'Submit for digital certificate issuance.'
        ],
        'requirements': ['Fayda ID', 'Business Address', 'Phone Number'],
        'priorityPoints': 150.0,
      },
      {
        'id': 'biz_license',
        'category': 'Business',
        'name': 'Business License Renewal',
        'description': 'Renew your business license using digital identity verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
        'type': 'online',
        'officialLink': 'https://www.moti.gov.et',
        'instructionSteps': [
          'Visit Ministry of Trade investment portal.',
          'Login with Fayda ID verification.',
          'Select business license renewal.',
          'Upload required documents and pay fees.',
          'Receive renewed license digitally.'
        ],
        'requirements': ['Fayda ID', 'Previous License', 'Tax Clearance', 'Renewal Fee'],
        'priorityPoints': 100.0,
      },
      {
        'id': 'biz_import_export',
        'category': 'Business',
        'name': 'Import/Export License',
        'description': 'Apply for import/export permits using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
        'type': 'online',
        'officialLink': 'https://www.moti.gov.et',
        'instructionSteps': [
          'Access the Trade Ministry portal.',
          'Verify identity with Fayda ID.',
          'Complete import/export application.',
          'Upload business documents and bank guarantee.',
          'Submit for review and approval.'
        ],
        'requirements': ['Fayda ID', 'TIN Certificate', 'Bank Guarantee', 'Business Plan'],
        'priorityPoints': 180.0,
      },
      {
        'id': 'biz_investment',
        'category': 'Business',
        'name': 'Investment Permit',
        'description': 'Register new investment projects with Ethiopian Investment Commission.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
        'type': 'online',
        'officialLink': 'https://www.investethiopia.gov.et',
        'instructionSteps': [
          'Visit EIC investment portal.',
          'Create investor profile with Fayda ID.',
          'Submit investment project details.',
          'Upload feasibility study and financial documents.',
          'Receive investment permit upon approval.'
        ],
        'requirements': ['Fayda ID', 'Project Proposal', 'Feasibility Study', 'Capital Proof'],
        'priorityPoints': 200.0,
      },
      {
        'id': 'biz_vat_registration',
        'category': 'Business',
        'name': 'VAT Registration',
        'description': 'Register for Value Added Tax with Ethiopian Revenue Authority.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
        'type': 'online',
        'officialLink': 'https://www.mofed.gov.et',
        'instructionSteps': [
          'Access Revenue Authority VAT portal.',
          'Verify business with Fayda ID and TIN.',
          'Complete VAT registration form.',
          'Upload business documents and financial statements.',
          'Receive VAT registration certificate.'
        ],
        'requirements': ['Fayda ID', 'TIN Certificate', 'Business License', 'Financial Statements'],
        'priorityPoints': 140.0,
      },
      {
        'id': 'biz_work_permit',
        'category': 'Business',
        'name': 'Foreign Work Permit',
        'description': 'Apply for work permits for foreign employees using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
        'type': 'online',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Access Ministry of Labor work permit portal.',
          'Submit work permit application for foreign employee.',
          'Verify employer identity with Fayda ID.',
          'Upload employee qualifications and medical certificates.',
          'Receive work permit upon approval.'
        ],
        'requirements': ['Fayda ID', 'Business License', 'Employee Qualifications', 'Medical Certificates'],
        'priorityPoints': 160.0,
      },
      {
        'id': 'biz_patent_registration',
        'category': 'Business',
        'name': 'Patent Registration',
        'description': 'Register intellectual property and patents with Ethiopian Intellectual Property Office.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
        'type': 'online',
        'officialLink': 'https://www.epo.gov.et',
        'instructionSteps': [
          'Visit Intellectual Property Office portal.',
          'Create inventor profile with Fayda ID.',
          'Submit patent application and technical drawings.',
          'Pay patent registration fees.',
          'Receive patent registration certificate.'
        ],
        'requirements': ['Fayda ID', 'Technical Drawings', 'Patent Application', 'Registration Fee'],
        'priorityPoints': 170.0,
      },
      {
        'id': 'biz_environmental_permit',
        'category': 'Business',
        'name': 'Environmental Impact Assessment',
        'description': 'Get environmental clearance for industrial projects.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
        'type': 'online',
        'officialLink': 'https://www.epa.gov.et',
        'instructionSteps': [
          'Access Environmental Protection Agency portal.',
          'Submit EIA study for project.',
          'Verify business identity with Fayda ID.',
          'Upload environmental impact assessment report.',
          'Receive environmental clearance certificate.'
        ],
        'requirements': ['Fayda ID', 'EIA Report', 'Project Details', 'Assessment Fee'],
        'priorityPoints': 150.0,
      },
      {
        'id': 'biz_food_license',
        'category': 'Business',
        'name': 'Food Business License',
        'description': 'Register food and beverage business with Ethiopian Food and Drug Authority.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
        'type': 'inPerson',
        'officialLink': 'https://www.efda.gov.et',
        'instructionSteps': [
          'Visit EFDA office with business documents.',
          'Verify identity with Fayda ID.',
          'Submit food business license application.',
          'Provide health certificates and kitchen inspection.',
          'Receive food business license.'
        ],
        'requirements': ['Fayda ID', 'Business Plan', 'Health Certificates', 'Kitchen Layout'],
        'priorityPoints': 120.0,
      },
      {
        'id': 'biz_construction_permit',
        'category': 'Business',
        'name': 'Construction Permit',
        'description': 'Get construction permits for building projects using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3135/3135706.png',
        'type': 'online',
        'officialLink': 'https://www.mowuds.gov.et',
        'instructionSteps': [
          'Access Urban Development construction portal.',
          'Submit building plans and architectural drawings.',
          'Verify contractor identity with Fayda ID.',
          'Pay permit fees and get approval.',
          'Receive construction permit.'
        ],
        'requirements': ['Fayda ID', 'Building Plans', 'Architectural Drawings', 'Permit Fees'],
        'priorityPoints': 130.0,
      },
      {
        'id': 'pub_driver_renew',
        'category': 'Public Service',
        'name': 'Driver License Renewal',
        'description': 'Renew your driving license digitally using Fayda identity.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2554/2554930.png',
        'type': 'online',
        'officialLink': 'https://www.transport.gov.et',
        'instructionSteps': [
          'Go to the Transport Authority digital portal.',
          'Validate your identity with Fayda ID.',
          'Submit medical certificate digital copy.',
          'Complete renewal requirements.',
          'Pick up your license or request delivery.'
        ],
        'requirements': ['Expired License', 'Medical Certificate', 'Fayda ID'],
        'priorityPoints': 50.0,
      },
      {
        'id': 'pub_vehicle_reg',
        'category': 'Public Service',
        'name': 'Vehicle Registration',
        'description': 'Register new vehicles or renew existing registration using Fayda.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2554/2554930.png',
        'type': 'online',
        'officialLink': 'https://www.transport.gov.et',
        'instructionSteps': [
          'Access Transport Authority vehicle portal.',
          'Verify ownership with Fayda ID.',
          'Upload vehicle purchase documents.',
          'Pay registration fees online.',
          'Receive digital registration certificate.'
        ],
        'requirements': ['Fayda ID', 'Vehicle Title', 'Insurance', 'Purchase Receipt'],
        'priorityPoints': 80.0,
      },
      {
        'id': 'pub_property_tax',
        'category': 'Public Service',
        'name': 'Property Tax Payment',
        'description': 'Pay annual property taxes through digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2554/2554930.png',
        'type': 'online',
        'officialLink': 'https://www.addisababa.gov.et',
        'instructionSteps': [
          'Visit city administration tax portal.',
          'Verify property ownership with Fayda ID.',
          'View property tax assessment.',
          'Pay taxes via mobile banking or Telebirr.',
          'Receive digital tax receipt.'
        ],
        'requirements': ['Fayda ID', 'Property ID', 'Bank Account', 'Previous Tax Receipt'],
        'priorityPoints': 60.0,
      },
      {
        'id': 'pub_utility_payment',
        'category': 'Public Service',
        'name': 'Utility Bill Payment',
        'description': 'Pay electricity and water bills using digital identity.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2554/2554930.png',
        'type': 'appBased',
        'officialLink': 'https://www.eepco.gov.et',
        'instructionSteps': [
          'Download utility payment app.',
          'Link account with Fayda ID verification.',
          'View current bill amounts.',
          'Pay through mobile banking or Telebirr.',
          'Receive payment confirmation.'
        ],
        'requirements': ['Fayda ID', 'Utility Account Number', 'Bank Account'],
        'priorityPoints': 30.0,
      },
      {
        'id': 'pub_national_id',
        'category': 'Public Service',
        'name': 'National ID Services',
        'description': 'Access national identification services using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2917/2917999.png',
        'type': 'online',
        'officialLink': 'https://www.eservices.gov.et/en',
        'instructionSteps': [
          'Visit Ethiopian eServices portal.',
          'Register or login with your credentials.',
          'Select National ID services.',
          'Complete verification process.',
          'Receive digital ID confirmation.'
        ],
        'requirements': ['Fayda ID', 'Email', 'Phone Number'],
        'priorityPoints': 100.0,
      },
      {
        'id': 'pub_voter_registration',
        'category': 'Public Service',
        'name': 'Voter Registration',
        'description': 'Register for voting using digital identity verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2917/2917999.png',
        'type': 'online',
        'officialLink': 'https://www.eservices.gov.et/en',
        'instructionSteps': [
          'Access eServices voter registration portal.',
          'Verify identity with Fayda ID.',
          'Complete voter registration form.',
          'Upload required documents.',
          'Receive voter registration confirmation.'
        ],
        'requirements': ['Fayda ID', 'Age Proof', 'Address Proof'],
        'priorityPoints': 80.0,
      },
      {
        'id': 'pub_business_permit',
        'category': 'Public Service',
        'name': 'Business Permit Registration',
        'description': 'Apply for business permits and licenses through eServices.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2917/2917999.png',
        'type': 'online',
        'officialLink': 'https://www.business.gov.et/',
        'instructionSteps': [
          'Visit Business Portal Ethiopia.',
          'Select business permit application.',
          'Verify with Fayda ID.',
          'Complete business registration.',
          'Submit required documents.'
        ],
        'requirements': ['Fayda ID', 'Business Plan', 'TIN Certificate'],
        'priorityPoints': 120.0,
      },
      {
        'id': 'pub_market_registration',
        'category': 'Public Service',
        'name': 'Market Registration',
        'description': 'Register for market access and trading permits.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2917/2917999.png',
        'type': 'online',
        'officialLink': 'https://www.eservices.gov.et/en',
        'instructionSteps': [
          'Access eServices market registration.',
          'Verify identity with Fayda ID.',
          'Select market type and location.',
          'Complete registration form.',
          'Receive market permit.'
        ],
        'requirements': ['Fayda ID', 'Business License', 'Market Location'],
        'priorityPoints': 60.0,
      },
      {
        'id': 'pub_waste_management',
        'category': 'Public Service',
        'name': 'Waste Management Services',
        'description': 'Register for waste collection and environmental services.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2917/2917999.png',
        'type': 'online',
        'officialLink': 'https://www.eservices.gov.et/en',
        'instructionSteps': [
          'Visit eServices environmental section.',
          'Select waste management services.',
          'Verify with Fayda ID.',
          'Complete service registration.',
          'Schedule waste collection.'
        ],
        'requirements': ['Fayda ID', 'Address Proof', 'Service Area'],
        'priorityPoints': 40.0,
      },
      {
        'id': 'pub_public_housing',
        'category': 'Public Service',
        'name': 'Public Housing Application',
        'description': 'Apply for public housing through digital services.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2917/2917999.png',
        'type': 'online',
        'officialLink': 'https://www.eservices.gov.et/en',
        'instructionSteps': [
          'Access eServices housing portal.',
          'Verify identity with Fayda ID.',
          'Complete housing application.',
          'Upload required documents.',
          'Track application status.'
        ],
        'requirements': ['Fayda ID', 'Income Proof', 'Family Information'],
        'priorityPoints': 90.0,
      },
      {
        'id': 'tel_sim_reg',
        'category': 'Telecom',
        'name': 'SIM Card Registration',
        'description': 'Link your Ethio Telecom or Safaricom SIM to Fayda.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3415/3415077.png',
        'type': 'online',
        'officialLink': 'https://www.ethiotelecom.et',
        'instructionSteps': [
          'Dial *804# or visit mobile operator app.',
          'Enter your 12-digit Fayda FIN.',
          'Upload a photo of your Fayda card if requested.',
          'Receive confirmation SMS.'
        ],
        'requirements': ['Active SIM', 'Fayda ID', '12-digit FIN'],
        'priorityPoints': 20.0,
      },
      {
        'id': 'tel_mobile_money',
        'category': 'Telecom',
        'name': 'Mobile Money Registration',
        'description': 'Register for Telebirr or M-Pesa mobile money services.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3415/3415077.png',
        'type': 'appBased',
        'officialLink': 'https://www.telebirr.et',
        'instructionSteps': [
          'Download mobile money app.',
          'Select registration with Fayda ID.',
          'Verify identity with biometric confirmation.',
          'Set up PIN and security questions.',
          'Start using mobile money services.'
        ],
        'requirements': ['Fayda ID', 'Smartphone', 'Bank Account'],
        'priorityPoints': 40.0,
      },
      {
        'id': 'tel_broadband',
        'category': 'Telecom',
        'name': 'Broadband Internet Subscription',
        'description': 'Subscribe to home broadband internet using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3415/3415077.png',
        'type': 'online',
        'officialLink': 'https://www.ethiotelecom.et',
        'instructionSteps': [
          'Visit telecom website broadband section.',
          'Choose internet package and verify with Fayda.',
          'Schedule installation appointment.',
          'Pay subscription fees online.',
          'Get broadband connection installed.'
        ],
        'requirements': ['Fayda ID', 'Address Proof', 'Payment Method'],
        'priorityPoints': 70.0,
      },
      {
        'id': 'tel_landline',
        'category': 'Telecom',
        'name': 'Landline Telephone Connection',
        'description': 'Apply for new landline telephone connection using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3415/3415077.png',
        'type': 'inPerson',
        'officialLink': 'https://www.ethiotelecom.et',
        'instructionSteps': [
          'Visit Ethio Telecom office.',
          'Verify identity with Fayda ID.',
          'Submit landline connection application.',
          'Provide address proof and installation details.',
          'Pay connection fees and schedule installation.'
        ],
        'requirements': ['Fayda ID', 'Address Proof', 'Connection Fee', 'Installation Details'],
        'priorityPoints': 50.0,
      },
      {
        'id': 'tel_international_calling',
        'category': 'Telecom',
        'name': 'International Calling Service',
        'description': 'Activate international calling service using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3415/3415077.png',
        'type': 'appBased',
        'officialLink': 'https://www.ethiotelecom.et',
        'instructionSteps': [
          'Access telecom mobile app.',
          'Verify identity with Fayda ID.',
          'Select international calling package.',
          'Pay subscription fees online.',
          'Receive international calling activation.'
        ],
        'requirements': ['Fayda ID', 'Active SIM', 'Payment Method', 'Passport Copy'],
        'priorityPoints': 40.0,
      },
      {
        'id': 'tel_roaming',
        'category': 'Telecom',
        'name': 'International Roaming Service',
        'description': 'Activate international roaming for travel using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3415/3415077.png',
        'type': 'appBased',
        'officialLink': 'https://www.ethiotelecom.et',
        'instructionSteps': [
          'Access telecom app before travel.',
          'Verify identity with Fayda ID.',
          'Select roaming destination countries.',
          'Pay roaming deposit and fees.',
          'Receive roaming service activation.'
        ],
        'requirements': ['Fayda ID', 'Active SIM', 'Travel Details', 'Roaming Deposit'],
        'priorityPoints': 45.0,
      },
      {
        'id': 'tel_postpaid',
        'category': 'Telecom',
        'name': 'Postpaid Plan Registration',
        'description': 'Convert from prepaid to postpaid mobile plan using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3415/3415077.png',
        'type': 'inPerson',
        'officialLink': 'https://www.ethiotelecom.et',
        'instructionSteps': [
          'Visit Ethio Telecom service center.',
          'Verify identity with Fayda ID.',
          'Submit postpaid plan application.',
          'Provide income proof and bank details.',
          'Receive postpaid SIM and service activation.'
        ],
        'requirements': ['Fayda ID', 'Income Proof', 'Bank Details', 'Current SIM'],
        'priorityPoints': 60.0,
      },
      {
        'id': 'tel_business_internet',
        'category': 'Telecom',
        'name': 'Business Internet Solution',
        'description': 'Get dedicated internet connection for business using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3415/3415077.png',
        'type': 'online',
        'officialLink': 'https://www.ethiotelecom.et',
        'instructionSteps': [
          'Access business solutions portal.',
          'Verify business identity with Fayda ID.',
          'Select business internet package.',
          'Submit business documents and requirements.',
          'Get business internet connection installed.'
        ],
        'requirements': ['Fayda ID', 'Business License', 'Bank Account', 'Technical Requirements'],
        'priorityPoints': 90.0,
      },
      {
        'id': 'tel_value_added',
        'category': 'Telecom',
        'name': 'Value-Added Services',
        'description': 'Subscribe to value-added services like caller tune, data bundles using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3415/3415077.png',
        'type': 'appBased',
        'officialLink': 'https://www.ethiotelecom.et',
        'instructionSteps': [
          'Access telecom mobile app.',
          'Verify identity with Fayda ID.',
          'Browse and select value-added services.',
          'Pay service fees through mobile money.',
          'Receive service activation confirmation.'
        ],
        'requirements': ['Fayda ID', 'Active SIM', 'Mobile Money', 'Smartphone'],
        'priorityPoints': 25.0,
      },
      // Vital Events Services
      {
        'id': 'vital_birth_reg',
        'category': 'Vital Events',
        'name': 'Birth Registration',
        'description': 'Register newborn births using Fayda digital identity.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2917/2917999.png',
        'type': 'online',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Access the eVIDA portal.',
          'Select Birth Registration.',
          'Enter parent Fayda FINs for verification.',
          'Upload birth certificate from hospital.',
          'Submit for digital birth certificate issuance.'
        ],
        'requirements': ['Parent Fayda IDs', 'Birth Certificate', 'Hospital Reference'],
        'priorityPoints': 80.0,
      },
      {
        'id': 'vital_marriage_reg',
        'category': 'Vital Events',
        'name': 'Marriage Registration',
        'description': 'Register your marriage certificate digitally with Fayda.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2672/2672299.png',
        'type': 'online',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Visit the Vital Events registration portal.',
          'Select Marriage Registration.',
          'Verify both spouses with Fayda IDs.',
          'Upload marriage certificate and witnesses.',
          'Receive digital marriage registration.'
        ],
        'requirements': ['Spouse Fayda IDs', 'Marriage Certificate', 'Witness IDs'],
        'priorityPoints': 60.0,
      },
      {
        'id': 'vital_death_reg',
        'category': 'Vital Events',
        'name': 'Death Registration',
        'description': 'Register death certificates using digital identity verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3142/3142156.png',
        'type': 'online',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Access the eVIDA death registration portal.',
          'Enter deceased Fayda FIN for verification.',
          'Upload medical certificate of death.',
          'Provide informant details and relationship.',
          'Submit for death certificate issuance.'
        ],
        'requirements': ['Deceased Fayda ID', 'Medical Certificate', 'Informant ID'],
        'priorityPoints': 40.0,
      },
      {
        'id': 'vital_divorce',
        'category': 'Vital Events',
        'name': 'Divorce Registration',
        'description': 'Register divorce certificates using digital identity verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3142/3142156.png',
        'type': 'inPerson',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Visit Vital Events office with court divorce decree.',
          'Verify both parties with Fayda IDs.',
          'Submit divorce registration application.',
          'Upload court decree and supporting documents.',
          'Receive divorce registration certificate.'
        ],
        'requirements': ['Both Fayda IDs', 'Court Decree', 'Witness IDs', 'Registration Fee'],
        'priorityPoints': 80.0,
      },
      {
        'id': 'vital_adoption',
        'category': 'Vital Events',
        'name': 'Adoption Registration',
        'description': 'Register legal adoption using digital identity verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3142/3142156.png',
        'type': 'inPerson',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Visit Vital Events office with adoption papers.',
          'Verify adoptive parents with Fayda IDs.',
          'Submit adoption registration application.',
          'Upload court adoption order and child documents.',
          'Receive adoption registration certificate.'
        ],
        'requirements': ['Parents Fayda IDs', 'Court Adoption Order', 'Child Documents', 'Registration Fee'],
        'priorityPoints': 100.0,
      },
      {
        'id': 'vital_certificate_correction',
        'category': 'Vital Events',
        'name': 'Certificate Correction',
        'description': 'Correct errors in vital event certificates using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3142/3142156.png',
        'type': 'inPerson',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Visit Vital Events office with error-containing certificate.',
          'Submit correction request with supporting documents.',
          'Verify identity with Fayda ID.',
          'Complete correction application form.',
          'Receive corrected certificate.'
        ],
        'requirements': ['Fayda ID', 'Certificate with Error', 'Supporting Documents', 'Correction Fee'],
        'priorityPoints': 60.0,
      },
      {
        'id': 'vital_certificate_copy',
        'category': 'Vital Events',
        'name': 'Certificate Copy Request',
        'description': 'Request copies of birth, marriage, or death certificates using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3142/3142156.png',
        'type': 'online',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Access eVIDA certificate request portal.',
          'Verify identity with Fayda ID.',
          'Select certificate type and provide reference number.',
          'Pay copy fees online.',
          'Receive certificate copy via delivery or pickup.'
        ],
        'requirements': ['Fayda ID', 'Certificate Reference', 'Payment Method', 'Delivery Address'],
        'priorityPoints': 35.0,
      },
      {
        'id': 'vital_name_change',
        'category': 'Vital Events',
        'name': 'Legal Name Change Registration',
        'description': 'Register legal name changes with vital events using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3142/3142156.png',
        'type': 'inPerson',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Visit Vital Events office with court name change order.',
          'Verify identity with current Fayda ID.',
          'Submit name change registration application.',
          'Upload court order and supporting documents.',
          'Receive updated vital records.'
        ],
        'requirements': ['Fayda ID', 'Court Name Change Order', 'Supporting Documents', 'Registration Fee'],
        'priorityPoints': 90.0,
      },
      {
        'id': 'vital_citizenship',
        'category': 'Vital Events',
        'name': 'Citizenship Certificate',
        'description': 'Apply for citizenship certificate using digital identity verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/3142/3142156.png',
        'type': 'inPerson',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Visit Immigration and Vital Events office.',
          'Submit citizenship application with supporting documents.',
          'Verify identity and eligibility with Fayda ID.',
          'Complete citizenship verification process.',
          'Receive citizenship certificate.'
        ],
        'requirements': ['Fayda ID', 'Parent Documents', 'Birth Certificate', 'Application Fee'],
        'priorityPoints': 120.0,
      },
      // Social Security Services
      {
        'id': 'social_pension',
        'category': 'Social Security',
        'name': 'Pension Registration',
        'description': 'Register for social security pension benefits using Fayda.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2936/2936830.png',
        'type': 'online',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Go to Social Security Agency portal.',
          'Select Pension Registration.',
          'Verify identity with Fayda ID.',
          'Upload employment history documents.',
          'Submit for pension eligibility assessment.'
        ],
        'requirements': ['Fayda ID', 'Employment History', 'Age Proof'],
        'priorityPoints': 120.0,
      },
      {
        'id': 'social_unemployment',
        'category': 'Social Security',
        'name': 'Unemployment Benefits',
        'description': 'Apply for unemployment benefits using digital identity.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2013/2013769.png',
        'type': 'online',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Access Social Security benefits portal.',
          'Select Unemployment Benefits.',
          'Verify with Fayda ID and employment status.',
          'Upload termination letter and ID.',
          'Submit for benefits processing.'
        ],
        'requirements': ['Fayda ID', 'Termination Letter', 'Bank Account'],
        'priorityPoints': 90.0,
      },
      {
        'id': 'social_health_insurance',
        'category': 'Social Security',
        'name': 'Health Insurance Registration',
        'description': 'Enroll in national health insurance program using Fayda.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2965/2965679.png',
        'type': 'online',
        'officialLink': 'https://www.ehi.gov.et',
        'instructionSteps': [
          'Visit Health Insurance portal.',
          'Select New Registration.',
          'Verify identity with Fayda ID.',
          'Choose insurance plan and payment method.',
          'Complete enrollment and receive coverage.'
        ],
        'requirements': ['Fayda ID', 'Payment Method', 'Dependent Information'],
        'priorityPoints': 100.0,
      },
      {
        'id': 'social_disability',
        'category': 'Social Security',
        'name': 'Disability Benefits Registration',
        'description': 'Register for disability benefits and support services using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2936/2936830.png',
        'type': 'inPerson',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Visit Social Security office with medical reports.',
          'Verify identity with Fayda ID.',
          'Submit disability benefits application.',
          'Upload medical assessment and work history.',
          'Receive disability benefits card.'
        ],
        'requirements': ['Fayda ID', 'Medical Reports', 'Work History', 'Application Form'],
        'priorityPoints': 110.0,
      },
      {
        'id': 'social_maternity',
        'category': 'Social Security',
        'name': 'Maternity Benefits Registration',
        'description': 'Register for maternity leave benefits and support using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2936/2936830.png',
        'type': 'online',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Access Social Security maternity benefits portal.',
          'Verify identity with Fayda ID.',
          'Submit maternity benefits application.',
          'Upload pregnancy confirmation and employment details.',
          'Receive maternity benefits approval.'
        ],
        'requirements': ['Fayda ID', 'Pregnancy Confirmation', 'Employment Details', 'Bank Account'],
        'priorityPoints': 95.0,
      },
      {
        'id': 'social_child_support',
        'category': 'Social Security',
        'name': 'Child Support Services',
        'description': 'Register for child support and family assistance programs.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2936/2936830.png',
        'type': 'inPerson',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Visit Social Security office with family documents.',
          'Verify parent identity with Fayda ID.',
          'Submit child support application.',
          'Provide income proof and family composition.',
          'Receive child support benefits.'
        ],
        'requirements': ['Fayda ID', 'Children Birth Certificates', 'Income Proof', 'Family Documents'],
        'priorityPoints': 85.0,
      },
      {
        'id': 'social_veteran',
        'category': 'Social Security',
        'name': 'Veteran Benefits Registration',
        'description': 'Register for military veteran benefits and pensions using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2936/2936830.png',
        'type': 'inPerson',
        'officialLink': 'https://www.mold.gov.et',
        'instructionSteps': [
          'Visit Ministry of Defense veteran affairs office.',
          'Verify military service with Fayda ID.',
          'Submit veteran benefits application.',
          'Upload military service records and discharge papers.',
          'Receive veteran benefits card.'
        ],
        'requirements': ['Fayda ID', 'Military Records', 'Discharge Papers', 'Service History'],
        'priorityPoints': 130.0,
      },
      {
        'id': 'social_widow',
        'category': 'Social Security',
        'name': 'Widow/Widower Pension',
        'description': 'Register for survivor pension benefits using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2936/2936830.png',
        'type': 'inPerson',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Visit Social Security office with spouse death certificate.',
          'Verify identity with Fayda ID.',
          'Submit survivor pension application.',
          'Upload marriage certificate and spouse records.',
          'Receive survivor pension benefits.'
        ],
        'requirements': ['Fayda ID', 'Spouse Death Certificate', 'Marriage Certificate', 'Bank Account'],
        'priorityPoints': 105.0,
      },
      {
        'id': 'social_elderly',
        'category': 'Social Security',
        'name': 'Elderly Support Program',
        'description': 'Register for elderly care and support services using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2936/2936830.png',
        'type': 'inPerson',
        'officialLink': 'https://www.molsa.gov.et',
        'instructionSteps': [
          'Visit Social Security elderly support office.',
          'Verify age and identity with Fayda ID.',
          'Submit elderly support application.',
          'Provide income proof and health assessment.',
          'Receive elderly support benefits.'
        ],
        'requirements': ['Fayda ID', 'Age Proof', 'Income Proof', 'Health Assessment'],
        'priorityPoints': 90.0,
      },
      // Healthcare Services
      {
        'id': 'health_medical_insurance',
        'category': 'Healthcare',
        'name': 'Private Medical Insurance',
        'description': 'Register for private health insurance with Ethiopian insurance companies.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2965/2965679.png',
        'type': 'online',
        'officialLink': 'https://www.nbe.gov.et',
        'instructionSteps': [
          'Visit insurance company website.',
          'Select health insurance plan.',
          'Verify identity with Fayda ID.',
          'Complete medical history questionnaire.',
          'Pay premium and receive insurance card.'
        ],
        'requirements': ['Fayda ID', 'Medical History', 'Payment Method', 'Photograph'],
        'priorityPoints': 95.0,
      },
      {
        'id': 'health_hospital_appointment',
        'category': 'Healthcare',
        'name': 'Hospital Appointment Booking',
        'description': 'Book appointments at public and private hospitals using digital verification.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2965/2965679.png',
        'type': 'appBased',
        'officialLink': 'https://www.moh.gov.et',
        'instructionSteps': [
          'Download hospital booking app or visit portal.',
          'Select hospital and department.',
          'Verify identity with Fayda ID.',
          'Choose preferred date and time.',
          'Receive appointment confirmation via SMS.'
        ],
        'requirements': ['Fayda ID', 'Smartphone', 'Previous Medical Records'],
        'priorityPoints': 75.0,
      },
      {
        'id': 'health_prescription_verification',
        'category': 'Healthcare',
        'name': 'Prescription Verification',
        'description': 'Verify and manage electronic prescriptions using digital identity.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2965/2965679.png',
        'type': 'appBased',
        'officialLink': 'https://www.fda.gov.et',
        'instructionSteps': [
          'Access e-prescription verification portal.',
          'Scan prescription QR code.',
          'Verify with Fayda ID authentication.',
          'Check medication authenticity and dosage.',
          'Receive verification confirmation.'
        ],
        'requirements': ['Fayda ID', 'Prescription', 'Smartphone'],
        'priorityPoints': 60.0,
      },
      {
        'id': 'health_covid_certificate',
        'category': 'Healthcare',
        'name': 'COVID-19 Vaccination Certificate',
        'description': 'Access and verify COVID-19 vaccination records using digital identity.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2965/2965679.png',
        'type': 'online',
        'officialLink': 'https://www.covid19.et',
        'instructionSteps': [
          'Visit Ministry of Health COVID portal.',
          'Login with Fayda ID verification.',
          'Access vaccination records.',
          'Download digital vaccination certificate.',
          'Share certificate for travel or work requirements.'
        ],
        'requirements': ['Fayda ID', 'Vaccination Card Number'],
        'priorityPoints': 50.0,
      },
      {
        'id': 'health_medical_license',
        'category': 'Healthcare',
        'name': 'Medical License Renewal',
        'description': 'Renew professional medical licenses for doctors, nurses, and healthcare workers.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2965/2965679.png',
        'type': 'online',
        'officialLink': 'https://www.moh.gov.et',
        'instructionSteps': [
          'Access Health Professionals licensing portal.',
          'Login with Fayda ID and license number.',
          'Upload continuing education certificates.',
          'Submit renewal application and fees.',
          'Receive renewed medical license.'
        ],
        'requirements': ['Fayda ID', 'Current License', 'CE Certificates', 'Renewal Fee'],
        'priorityPoints': 110.0,
      },
      {
        'id': 'health_health_card',
        'category': 'Healthcare',
        'name': 'National Health Card Registration',
        'description': 'Register for national health card for accessing public healthcare services.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2965/2965679.png',
        'type': 'inPerson',
        'officialLink': 'https://www.moh.gov.et',
        'instructionSteps': [
          'Visit local health center.',
          'Verify identity with Fayda ID.',
          'Complete health registration form.',
          'Provide family member information.',
          'Receive national health card.'
        ],
        'requirements': ['Fayda ID', 'Family Information', 'Photograph', 'Registration Fee'],
        'priorityPoints': 85.0,
      },
      {
        'id': 'health_telemedicine',
        'category': 'Healthcare',
        'name': 'Telemedicine Service Access',
        'description': 'Register for telemedicine consultations with Ethiopian healthcare providers.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2965/2965679.png',
        'type': 'appBased',
        'officialLink': 'https://www.telemedicine.et',
        'instructionSteps': [
          'Download telemedicine app.',
          'Create profile with Fayda ID verification.',
          'Select specialty and doctor.',
          'Schedule video consultation.',
          'Attend consultation and receive e-prescription.'
        ],
        'requirements': ['Fayda ID', 'Smartphone', 'Internet Connection', 'Payment Method'],
        'priorityPoints': 80.0,
      },
      {
        'id': 'health_blood_donation',
        'category': 'Healthcare',
        'name': 'Blood Donation Registration',
        'description': 'Register as blood donor and manage donation schedule using digital identity.',
        'logo': 'https://cdn-icons-png.flaticon.com/512/2965/2965679.png',
        'type': 'appBased',
        'officialLink': 'https://www.nbts.gov.et',
        'instructionSteps': [
          'Access National Blood Transfusion Service portal.',
          'Register as donor with Fayda ID verification.',
          'Complete health questionnaire.',
          'Schedule donation appointment.',
          'Receive donor card and donation reminders.'
        ],
        'requirements': ['Fayda ID', 'Health Information', 'Contact Details'],
        'priorityPoints': 40.0,
      },
    ];

    for (final service in services) {
      final id = service['id'] as String;
      await dbRef.child(id).set(service);
      debugPrint('Seeded service: $id');
    }
  }
}
